# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

default_language_version:
  python: python3

ci:
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit suggestions'
  autoupdate_schedule: quarterly
  # submodules: true

exclude: 'tests/(ioi_parity|mech_interp_parity)/.*'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
        args: ['--maxkb=350', '--enforce-all']
        exclude: |
            (?x)^(
                docs/source/_static/images/fts/fts_explicit_loss_anim.gif
            )$
      - id: detect-private-key

  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
  # temporarily disabling until the pre-commit hook allows per-line ignores to avoid certain errors with jaxtyping
  # - repo: https://github.com/asottile/pyupgrade
  #   rev: v3.19.1
  #   hooks:
  #     - id: pyupgrade
  #       args: [--py310-plus]
  #       name: Upgrade code

  - repo: https://github.com/myint/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        args: [--in-place, --wrap-summaries=115, --wrap-descriptions=120]
        exclude: |
          (?x)^(?:
            src/interpretune/base/components/core\.py
            |src/interpretune/base/components/mixins\.py
            |src/interpretune/base/hooks\.py
          )$

  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
        name: Unused noqa

  # disabled until python 3.13 is supported (to allow exclude option)
  # - repo: https://github.com/executablebooks/mdformat
  #   rev: 0.7.19
  #   hooks:
  #     - id: mdformat
  #       additional_dependencies:
  #         - mdformat-gfm
  #         - mdformat_frontmatter
  #       exclude: "CHANGELOG.md", "**/*.prompt.md"

  - repo: local
    hooks:
      - id: publish-notebooks
        name: Publish notebooks if changed
        entry: python scripts/publish_notebooks.py
        language: system
        files: ^src/it_examples/notebooks/dev/.*\.ipynb$
        pass_filenames: false

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.12.10'
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
